title: Yuki Note
url: https://yukinote.net
author: yknk
lang: ja

twitter_username: yknkjp
github_username: yknk
rss: RSS

permalink: /:year/:month/:day/:title/
timezone: Asia/Tokyo

sass:
  style: expanded

minima:
  date_format: "%Y/%m/%d"

header_pages:
  - about.md

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - netlify.toml
  - README.md
