[build]
publish = "_site"
command = "jekyll build"

[context.production.environment]
JEKYLL_ENV = "production"

[[redirects]]
from = "http://yukinote-net.netlify.com/*"
to = "https://yukinote-net.netlify.com/:splat"
status = 301
force = true

[[headers]]
for = "/*"

[headers.values]
Content-Security-Policy = "default-src https:; script-src https: 'unsafe-inline'; style-src https: 'unsafe-inline'"
Referrer-Policy = "strict-origin-when-cross-origin"
Strict-Transport-Security = "max-age=15552000"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "SAMEORIGIN"
X-Robots-Tag = "noarchive"
X-XSS-Protection = "1; mode=block"
